title: VokunGahrotLaas
email: maxence.michot.pro@gmail.com
description: >-
  Just a test website for me...
baseurl: /
url: https://vokungharotlaas.fr
domain: vokungahrotlaas.fr
twitter_username: VokunGahrotLaas
github_username:  VokunGahrotLaas

remote_theme: dracula/gh-pages
plugins:
gems:
- jekyll-seo-tag

show_downloads: false
google_analytics:
show_header: false

icon: ./icon.jpg
colorspace: purple

