title: VokunGahrotLaas
author:
  name: VokunGahrotLaas
  email: maxence.michot.pro@gmail.com
description: >
  Just a test website for me...
show_excerpts: true
google_analytics: 226898178

minima:
  date_format: "%b %-d, %Y"
  skin: dark
  social_links:
    twitter: VokunGahrotLaas
    github:  VokunGahrotLaas

header_pages:
  - about.md

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
