title: VokunGahrotLaas
author:
  name: VokunGahrotLaas
  email: maxence.michot.pro@gmail.com
description: >
  Just a test website for me...
show_excerpts: true
google_analytics: G-VG439HTLK1

minima:
  date_format: "%b %-d, %Y"
  skin: dark
  social_links:
    twitter: VokunGahrotLaas
    github:  VokunGahrotLaas
    linkedin: maxence-michot

header_pages:
  - about.md

remote_theme: jekyll/minima
#theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
  - jekyll-seo-tag
