title: Maxence MICHOT
author:
  name: Maxence MICHOT
  email: maxence.michot.pro@gmail.com
description: >
  Welcome to my personal website.
show_excerpts: true
google_analytics: G-VG439HTLK1

minima:
  date_format: "%b %-d, %Y"
  skin: dark
  social_links:
    twitter: VokunGahrotLaas
    github:  VokunGahrotLaas
    linkedin: maxence-michot

header_pages:
  - about.md

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
